using NexoCommerceAI.Domain.Entities;
using Xunit;

namespace NexoCommerceAI.UnitTests.Domain.Entities;

public class ProductTests
{
    private readonly Guid _categoryId = Guid.NewGuid();
    
    [Fact]
    public void Create_WithAllFields_ShouldCreateProduct()
    {
        // Act
        var product = Product.Create(
            "Gaming Laptop",
            _categoryId,
            slug: "gaming-laptop",
            description: "High-performance gaming laptop",
            price: 1299.99m,
            compareAtPrice: 1499.99m,
            sku: "SKU-001",
            stock: 10,
            isFeatured: true);
        
        // Assert
        Assert.Equal("Gaming Laptop", product.Name);
        Assert.Equal("gaming-laptop", product.Slug);
        Assert.Equal("High-performance gaming laptop", product.Description);
        Assert.Equal(1299.99m, product.Price);
        Assert.Equal(1499.99m, product.CompareAtPrice);
        Assert.Equal("SKU-001", product.Sku);
        Assert.Equal(10, product.Stock);
        Assert.True(product.IsFeatured);
        Assert.Equal(_categoryId, product.CategoryId);
        Assert.True(product.IsActive);
        Assert.False(product.IsDeleted);
    }
    
    [Fact]
    public void Create_WithMinimalFields_ShouldCreateProductWithAutoGeneratedSlugAndSku()
    {
        // Act
        var product = Product.Create("Laptop", _categoryId, price: 999.99m, stock: 5);
        
        // Assert
        Assert.Equal("Laptop", product.Name);
        Assert.Equal("laptop", product.Slug); // Auto-generated
        Assert.Null(product.Description);
        Assert.Equal(999.99m, product.Price);
        Assert.Null(product.CompareAtPrice);
        Assert.NotNull(product.Sku); // Auto-generated SKU
        Assert.Equal(5, product.Stock);
        Assert.False(product.IsFeatured);
        Assert.Equal(_categoryId, product.CategoryId);
    }
    
    [Fact]
    public void Create_WithCustomSlug_ShouldUseProvidedSlug()
    {
        // Act
        var product = Product.Create("Laptop", _categoryId, slug: "custom-laptop-slug");
        
        // Assert
        Assert.Equal("Laptop", product.Name);
        Assert.Equal("custom-laptop-slug", product.Slug);
    }
    
    [Fact]
    public void Create_WithCustomSku_ShouldUseProvidedSku()
    {
        // Act
        var product = Product.Create("Laptop", _categoryId, sku: "CUSTOM-SKU-123");
        
        // Assert
        Assert.Equal("CUSTOM-SKU-123", product.Sku);
    }
    
    public static IEnumerable<object?[]> InvalidProductData => new List<object?[]>
    {
        new object?[] { "", "laptop", "Desc", 100m, null, "SKU-001", 10 },
        new object?[] { null, "laptop", "Desc", 100m, null, "SKU-001", 10 },
        new object?[] { "Laptop", "", "Desc", 100m, null, "SKU-001", 10 },
        new object?[] { "Laptop", null, "Desc", 100m, null, "SKU-001", 10 },
        new object?[] { "Laptop", "laptop", "Desc", 0m, null, "SKU-001", 10 },
        new object?[] { "Laptop", "laptop", "Desc", -10m, null, "SKU-001", 10 },
        new object?[] { "Laptop", "laptop", "Desc", 100m, null, "", 10 },
        new object?[] { "Laptop", "laptop", "Desc", 100m, null, null, 10 },
        new object?[] { "Laptop", "laptop", "Desc", 100m, null, "SKU-001", -5 },
        new object?[] { "Laptop", "laptop", new string('A', 2001), 100m, null, "SKU-001", 10 }
    };

    [Theory]
    [MemberData(nameof(InvalidProductData))]
    public void Create_WithInvalidData_ShouldThrowException(string name, string slug, string description, 
        decimal price, decimal? compareAtPrice, 
        string sku, int stock)
    {
        // Act & Assert
        Assert.Throws<ArgumentException>(() => 
            Product.Create(name, _categoryId, slug, description, price, compareAtPrice, sku, stock));
    }
    
    [Fact]
    public void Create_WithEmptyCategoryId_ShouldThrowException()
    {
        // Act & Assert
        Assert.Throws<ArgumentException>(() => 
            Product.Create("Laptop", Guid.Empty));
    }
    
    [Fact]
    public void Create_WithInvalidCompareAtPrice_ShouldThrowException()
    {
        // Act & Assert - CompareAtPrice less than regular price
        Assert.Throws<ArgumentException>(() => 
            Product.Create("Laptop", _categoryId, price: 1000m, compareAtPrice: 900m));
    }
    
    [Fact]
    public void Create_WithCompareAtPriceEqualToRegularPrice_ShouldThrowException()
    {
        // Act & Assert
        Assert.Throws<ArgumentException>(() => 
            Product.Create("Laptop", _categoryId, price: 1000m, compareAtPrice: 1000m));
    }
    
    [Fact]
    public void CreateSimple_ShouldCreateProductWithRequiredFields()
    {
        // Act
        var product = Product.CreateSimple("Laptop", "High-performance laptop", 1299.99m, 10, _categoryId);
        
        // Assert
        Assert.Equal("Laptop", product.Name);
        Assert.Equal("High-performance laptop", product.Description);
        Assert.Equal(1299.99m, product.Price);
        Assert.Equal(10, product.Stock);
        Assert.Equal(_categoryId, product.CategoryId);
        Assert.NotNull(product.Slug);
        Assert.NotNull(product.Sku);
    }
    
    [Fact]
    public void Update_WithAllFields_ShouldUpdateProduct()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 999.99m, stock: 5);
        var newCategoryId = Guid.NewGuid();
        var originalUpdatedAt = product.UpdatedAt;
        
        // Act
        product.Update(
            name: "Gaming Laptop",
            slug: "gaming-laptop",
            description: "New description",
            price: 1299.99m,
            compareAtPrice: 1499.99m,
            sku: "NEW-SKU-001",
            stock: 15,
            isFeatured: true,
            categoryId: newCategoryId);
        
        // Assert
        Assert.Equal("Gaming Laptop", product.Name);
        Assert.Equal("gaming-laptop", product.Slug);
        Assert.Equal("New description", product.Description);
        Assert.Equal(1299.99m, product.Price);
        Assert.Equal(1499.99m, product.CompareAtPrice);
        Assert.Equal("NEW-SKU-001", product.Sku);
        Assert.Equal(15, product.Stock);
        Assert.True(product.IsFeatured);
        Assert.Equal(newCategoryId, product.CategoryId);
        Assert.NotNull(product.UpdatedAt);
        Assert.NotEqual(originalUpdatedAt, product.UpdatedAt);
    }
    
    [Fact]
    public void Update_WithPartialFields_ShouldUpdateOnlyProvidedFields()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 999.99m, stock: 5);
        var originalSlug = product.Slug;
        var originalSku = product.Sku;
        
        // Act
        product.Update(name: "Gaming Laptop", price: 1299.99m);
        
        // Assert
        Assert.Equal("Gaming Laptop", product.Name);
        Assert.Equal("gaming-laptop", product.Slug); // Auto-generated from new name
        Assert.Equal(1299.99m, product.Price);
        Assert.Equal(originalSku, product.Sku); // SKU unchanged
        Assert.Equal(5, product.Stock); // Stock unchanged
    }
    
    [Fact]
    public void Update_WithOnlyName_ShouldRegenerateSlug()
    {
        // Arrange
        var product = Product.Create("Old Name", _categoryId);
        var originalSlug = product.Slug;
        var originalSku = product.Sku;
        
        // Act
        product.Update(name: "New Name");
        
        // Assert
        Assert.Equal("New Name", product.Name);
        Assert.Equal("new-name", product.Slug);
        Assert.NotEqual(originalSlug, product.Slug);
        Assert.Equal(originalSku, product.Sku);
    }
    
    [Fact]
    public void UpdateSlug_ShouldUpdateOnlySlug()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId);
        var originalName = product.Name;
        var originalSku = product.Sku;
        
        // Act
        product.UpdateSlug("custom-slug");
        
        // Assert
        Assert.Equal(originalName, product.Name);
        Assert.Equal("custom-slug", product.Slug);
        Assert.Equal(originalSku, product.Sku);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void UpdatePrice_WithValidPrice_ShouldUpdatePrice()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m);
        var originalUpdatedAt = product.UpdatedAt;
        
        // Act
        product.UpdatePrice(899.99m);
        
        // Assert
        Assert.Equal(899.99m, product.Price);
        Assert.Null(product.CompareAtPrice);
        Assert.NotNull(product.UpdatedAt);
        Assert.NotEqual(originalUpdatedAt, product.UpdatedAt);
    }
    
    [Fact]
    public void UpdatePrice_WithCompareAtPrice_ShouldUpdateBoth()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m);
        
        // Act
        product.UpdatePrice(899.99m, 1299.99m);
        
        // Assert
        Assert.Equal(899.99m, product.Price);
        Assert.Equal(1299.99m, product.CompareAtPrice);
    }
    
    [Theory]
    [InlineData(0)]
    [InlineData(-100)]
    [InlineData(1000001)]
    public void UpdatePrice_WithInvalidPrice_ShouldThrowException(decimal invalidPrice)
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m);
        
        // Act & Assert
        Assert.Throws<ArgumentException>(() => product.UpdatePrice(invalidPrice));
    }
    
    [Fact]
    public void UpdatePrice_WithInvalidCompareAtPrice_ShouldThrowException()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m);
        
        // Act & Assert
        Assert.Throws<ArgumentException>(() => product.UpdatePrice(899.99m, 800m));
    }
    
    [Fact]
    public void GetDiscountPercentage_WhenOnSale_ShouldReturnCorrectPercentage()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 899.99m, compareAtPrice: 1299.99m);
        
        // Act
        var discount = product.GetDiscountPercentage();
        
        // Assert
        Assert.Equal(30.77m, discount); // (1299.99 - 899.99) / 1299.99 * 100 = 30.77
    }
    
    [Fact]
    public void GetDiscountPercentage_WhenNotOnSale_ShouldReturnZero()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m);
        
        // Act
        var discount = product.GetDiscountPercentage();
        
        // Assert
        Assert.Equal(0, discount);
    }
    
    [Fact]
    public void GetDiscountPercentage_WithCompareAtPriceLower_ShouldReturnZero()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, compareAtPrice: 900m);
        
        // Act
        var discount = product.GetDiscountPercentage();
        
        // Assert
        Assert.Equal(0, discount);
    }
    
    [Fact]
    public void IsOnSale_WithCompareAtPriceGreater_ShouldReturnTrue()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 899.99m, compareAtPrice: 1299.99m);
        
        // Act & Assert
        Assert.True(product.IsOnSale());
    }
    
    [Fact]
    public void IsOnSale_WithoutCompareAtPrice_ShouldReturnFalse()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m);
        
        // Act & Assert
        Assert.False(product.IsOnSale());
    }
    
    [Fact]
    public void IsOnSale_WithCompareAtPriceLower_ShouldReturnFalse()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, compareAtPrice: 900m);
        
        // Act & Assert
        Assert.False(product.IsOnSale());
    }
    
    [Theory]
    [InlineData(10, true)]
    [InlineData(1, true)]
    [InlineData(0, false)]
    public void IsInStock_ShouldReturnCorrectStatus(int stock, bool expected)
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, stock: stock);
        
        // Act & Assert
        Assert.Equal(expected, product.IsInStock());
    }
    
    [Theory]
    [InlineData(3, 5, true)]
    [InlineData(5, 5, true)]
    [InlineData(6, 5, false)]
    [InlineData(0, 5, false)]
    public void IsLowStock_ShouldReturnCorrectStatus(int stock, int threshold, bool expected)
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, stock: stock);
        
        // Act
        var isLowStock = product.IsLowStock(threshold);
        
        // Assert
        Assert.Equal(expected, isLowStock);
    }
    
    [Fact]
    public void IsLowStock_WithDefaultThreshold_ShouldUseThreshold5()
    {
        // Arrange
        var productWithStock3 = Product.Create("Laptop", _categoryId, price: 1000m, stock: 3);
        var productWithStock6 = Product.Create("Mouse", _categoryId, price: 1000m, stock: 6);
        
        // Act & Assert
        Assert.True(productWithStock3.IsLowStock());
        Assert.False(productWithStock6.IsLowStock());
    }
    
    [Fact]
    public void UpdateStock_WithValidStock_ShouldUpdate()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, stock: 10);
        
        // Act
        product.UpdateStock(25);
        
        // Assert
        Assert.Equal(25, product.Stock);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void UpdateStock_WithZeroStock_ShouldUpdate()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, stock: 10);
        
        // Act
        product.UpdateStock(0);
        
        // Assert
        Assert.Equal(0, product.Stock);
        Assert.False(product.IsInStock());
    }
    
    [Fact]
    public void UpdateStock_WithNegativeStock_ShouldThrowException()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, price: 1000m, stock: 10);
        
        // Act & Assert
        Assert.Throws<ArgumentException>(() => product.UpdateStock(-5));
    }
    
    [Fact]
    public void MarkAsFeatured_ShouldSetFeaturedTrue()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId);
        Assert.False(product.IsFeatured);
        
        // Act
        product.MarkAsFeatured();
        
        // Assert
        Assert.True(product.IsFeatured);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void UnmarkAsFeatured_ShouldSetFeaturedFalse()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, isFeatured: true);
        
        // Act
        product.UnmarkAsFeatured();
        
        // Assert
        Assert.False(product.IsFeatured);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void IncreaseStock_WithValidQuantity_ShouldIncreaseStock()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, stock: 10);
        
        // Act
        product.IncreaseStock(5);
        
        // Assert
        Assert.Equal(15, product.Stock);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Theory]
    [InlineData(0)]
    [InlineData(-5)]
    public void IncreaseStock_WithInvalidQuantity_ShouldThrowException(int quantity)
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, stock: 10);
        
        // Act & Assert
        Assert.Throws<ArgumentException>(() => product.IncreaseStock(quantity));
    }
    
    [Fact]
    public void DecreaseStock_WithValidQuantity_ShouldDecreaseStock()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, stock: 10);
        
        // Act
        product.DecreaseStock(3);
        
        // Assert
        Assert.Equal(7, product.Stock);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void DecreaseStock_WithExactStock_ShouldSetToZero()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, stock: 10);
        
        // Act
        product.DecreaseStock(10);
        
        // Assert
        Assert.Equal(0, product.Stock);
        Assert.False(product.IsInStock());
    }
    
    [Fact]
    public void DecreaseStock_WithInsufficientStock_ShouldThrowException()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId, stock: 10);
        
        // Act & Assert
        var exception = Assert.Throws<InvalidOperationException>(() => product.DecreaseStock(15));
        Assert.Contains("Not enough stock available", exception.Message);
        Assert.Contains("Current stock: 10", exception.Message);
        Assert.Contains("requested: 15", exception.Message);
    }
    
    [Fact]
    public void SoftDelete_ShouldMarkAsDeletedAndInactive()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId);
        Assert.True(product.IsActive);
        Assert.False(product.IsDeleted);
        
        // Act
        product.SoftDelete();
        
        // Assert
        Assert.True(product.IsDeleted);
        Assert.False(product.IsActive);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void Deactivate_ShouldSetActiveFalse()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId);
        Assert.True(product.IsActive);
        
        // Act
        product.Deactivate();
        
        // Assert
        Assert.False(product.IsActive);
        Assert.False(product.IsDeleted); // Should still be not deleted
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void Activate_ShouldSetActiveTrue()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId);
        product.Deactivate();
        Assert.False(product.IsActive);
        
        // Act
        product.Activate();
        
        // Assert
        Assert.True(product.IsActive);
        Assert.NotNull(product.UpdatedAt);
    }
    
    [Fact]
    public void GenerateSku_ShouldCreateUniqueSkus()
    {
        // Arrange & Act
        var product1 = Product.Create("Laptop", _categoryId);
        var product2 = Product.Create("Mouse", _categoryId);
        var product3 = Product.Create("Keyboard", _categoryId);
        
        // Assert
        Assert.NotEqual(product1.Sku, product2.Sku);
        Assert.NotEqual(product1.Sku, product3.Sku);
        Assert.NotEqual(product2.Sku, product3.Sku);
        
        // Verify SKU format (PREFIX-XXXXXXXX)
        Assert.Matches(@"^[A-Z]{4}-[A-Z0-9]{8}$", product1.Sku);
        Assert.Matches(@"^[A-Z]{4}-[A-Z0-9]{8}$", product2.Sku);
        Assert.Matches(@"^[A-Z]{4}-[A-Z0-9]{8}$", product3.Sku);
    }
    
    [Fact]
    public void GenerateSku_ShouldUseFirst4LettersOfName()
    {
        // Act
        var product = Product.Create("Gaming Laptop Pro", _categoryId);
        
        // Assert
        Assert.StartsWith("GAMI-", product.Sku);
    }
    
    [Fact]
    public void MultipleCreates_ShouldCreateIndependentProducts()
    {
        // Act
        var product1 = Product.Create("Laptop", _categoryId, price: 1000m, stock: 10);
        var product2 = Product.Create("Mouse", _categoryId, price: 30m, stock: 50);
        
        // Assert
        Assert.NotEqual(product1.Id, product2.Id);
        Assert.NotEqual(product1.Sku, product2.Sku);
        Assert.NotEqual(product1.Slug, product2.Slug);
        Assert.Equal(1000m, product1.Price);
        Assert.Equal(30m, product2.Price);
    }
    
    [Fact]
    public void ChainOperations_ShouldUpdateUpdatedAtEachTime()
    {
        // Arrange
        var product = Product.Create("Laptop", _categoryId);
        var firstUpdate = product.UpdatedAt;
        
        // Act
        System.Threading.Thread.Sleep(10); // Ensure time difference
        product.UpdatePrice(900m);
        var secondUpdate = product.UpdatedAt;
        
        System.Threading.Thread.Sleep(10);
        product.IncreaseStock(5);
        var thirdUpdate = product.UpdatedAt;
        
        // Assert
        Assert.NotEqual(firstUpdate, secondUpdate);
        Assert.NotEqual(secondUpdate, thirdUpdate);
        Assert.True(thirdUpdate > secondUpdate);
        Assert.True(secondUpdate > firstUpdate);
    }
}